#!/usr/bin/env node
/**
 * Feature Plan Codegen
 *
 * Reads `src/main/initializers/*.spec.ts`, computes per-phase dependency batches
 * via topological sort, and emits `src/main/generated/featurePlan.ts`.
 *
 * Replaces the runtime topo-sort that used to live in the 485-line
 * FeatureManager. At runtime, `featureRunner` simply walks the precomputed plan.
 *
 * Parsing strategy: spec files have a strict shape (name/phase/dependencies as
 * literal strings/arrays inside `as const satisfies readonly FeatureSpec[]`).
 * We extract those fields with regex — no TS execution required.
 *
 * Exposed as both:
 *   - A standalone function `generateFeaturePlan({ projectRoot, write })`
 *     for build scripts and tests.
 *   - An Rsbuild plugin via the default export, runnable in any Rsbuild
 *     pipeline so the generated file is always up to date with the specs.
 */

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const PHASES = ['security', 'critical', 'ui', 'deferred'];

const HEADER = `/**
 * Auto-generated by \`scripts/featurePlanPlugin.js\`. DO NOT EDIT.
 *
 * The plugin reads \`src/main/initializers/*.spec.ts\`, runs a topological sort
 * keyed by \`dependencies\`, and emits a phase → dependency-batched plan that
 * \`featureRunner\` walks at startup.
 */
`;

/**
 * Extract feature entries from a spec source file.
 * Returns array of { name, phase, dependencies, required }.
 */
function parseSpecFile(source) {
  const entries = [];
  // Match each object literal inside the spec array:
  //   { name: 'x', phase: 'y', ... }
  // Object literals are delimited by balanced braces; we use a stateful walker
  // because regex alone cannot handle nested braces (init bodies contain {}).
  const arrayStart = source.search(/=\s*\[/);
  if (arrayStart < 0) return entries;
  let i = source.indexOf('[', arrayStart) + 1;
  let depth = 0;
  let objectStart = -1;
  for (; i < source.length; i++) {
    const ch = source[i];
    if (ch === '{') {
      if (depth === 0) objectStart = i;
      depth++;
    } else if (ch === '}') {
      depth--;
      if (depth === 0 && objectStart >= 0) {
        const objSrc = source.slice(objectStart, i + 1);
        const entry = extractTopLevelFields(objSrc);
        if (entry && entry.name && entry.phase) entries.push(entry);
        objectStart = -1;
      }
    } else if (ch === ']' && depth === 0) {
      break;
    }
  }
  return entries;
}

/** Extract `name`, `phase`, `required`, `dependencies` from a single object literal. */
function extractTopLevelFields(objSrc) {
  // Scoped to the top level: walk braces and only inspect property assignments
  // at depth 1 (the object's own properties), not anything nested in init/cleanup.
  const result = {};
  let depth = 0;
  let i = 0;
  // Skip opening brace
  while (i < objSrc.length && objSrc[i] !== '{') i++;
  i++;
  depth = 1;
  let propStart = i;
  for (; i < objSrc.length; i++) {
    const ch = objSrc[i];
    if (ch === '{' || ch === '[' || ch === '(') depth++;
    else if (ch === '}' || ch === ']' || ch === ')') depth--;
    if (depth === 1 && ch === ',') {
      maybeAssignProp(objSrc.slice(propStart, i), result);
      propStart = i + 1;
    }
    if (depth === 0) {
      maybeAssignProp(objSrc.slice(propStart, i), result);
      break;
    }
  }
  return result;
}

function maybeAssignProp(snippet, out) {
  // Match the simple assignments only; ignore init/cleanup/description.
  const m = snippet.match(/^\s*(\w+)\s*:\s*([\s\S]+)$/);
  if (!m) return;
  const [, key, rawValue] = m;
  const value = rawValue.trim();
  if (key === 'name' || key === 'phase') {
    const sm = value.match(/^['"]([^'"]+)['"]/);
    if (sm) out[key] = sm[1];
  } else if (key === 'required') {
    out.required = /^true\b/.test(value);
  } else if (key === 'dependencies') {
    const am = value.match(/^\[([^\]]*)\]/);
    if (am) {
      out.dependencies = [...am[1].matchAll(/['"]([^'"]+)['"]/g)].map((m) => m[1]);
    }
  }
}

/**
 * Topologically sort entries within a single phase, returning batches.
 * Cross-phase deps are tolerated (assumed to be initialized in a prior phase).
 * Throws on cycle detection.
 */
function batchByDependencies(entries, phase, knownNames) {
  const inPhase = entries.filter((e) => e.phase === phase);
  const inPhaseNames = new Set(inPhase.map((e) => e.name));

  // Cycle detection via DFS
  const visiting = new Set();
  const visited = new Set();
  const visit = (e) => {
    if (visited.has(e.name)) return;
    if (visiting.has(e.name)) {
      throw new Error(`[featurePlanPlugin] Circular dependency detected at '${e.name}'`);
    }
    visiting.add(e.name);
    for (const dep of e.dependencies || []) {
      const next = inPhase.find((x) => x.name === dep);
      if (next) visit(next);
      else if (!knownNames.has(dep)) {
        throw new Error(
          `[featurePlanPlugin] '${e.name}' depends on unknown feature '${dep}'`
        );
      }
    }
    visiting.delete(e.name);
    visited.add(e.name);
  };
  for (const e of inPhase) visit(e);

  // Greedy batch assignment: a feature lands in batch N once all in-phase deps
  // are in batches < N.
  const batches = [];
  const assigned = new Set();
  let remaining = [...inPhase];
  while (remaining.length) {
    const ready = remaining.filter((e) =>
      (e.dependencies || []).every((d) => !inPhaseNames.has(d) || assigned.has(d))
    );
    if (!ready.length) {
      throw new Error(
        `[featurePlanPlugin] Unresolvable dependencies in '${phase}': ${remaining.map((e) => e.name).join(', ')}`
      );
    }
    batches.push(ready);
    for (const e of ready) assigned.add(e.name);
    remaining = remaining.filter((e) => !assigned.has(e.name));
  }
  return batches;
}

function emitPlan(specFiles, plan) {
  const importLines = specFiles.map(
    ({ exportName, importPath }) => `import { ${exportName} } from '${importPath}';`
  );
  const phaseLines = PHASES.map((phase) => {
    const batches = plan[phase] || [];
    const inner = batches
      .map((batch) => `    [${batch.map((name) => `get('${name}')`).join(', ')}]`)
      .join(',\n');
    return `  ${phase}: [\n${inner}\n  ]`;
  });
  return [
    HEADER,
    `import type { FeatureSpec, FeaturePriority } from '../utils/featureConfigTypes.js';`,
    ...importLines,
    ``,
    `const ALL_SPECS: readonly FeatureSpec[] = [`,
    ...specFiles.map(({ exportName }) => `  ...${exportName},`),
    `];`,
    ``,
    `const byName = new Map<string, FeatureSpec>(ALL_SPECS.map((s) => [s.name, s]));`,
    `const get = (name: string): FeatureSpec => {`,
    `  const spec = byName.get(name);`,
    `  if (!spec) throw new Error(\`[FEATURE_PLAN] Missing spec for '\${name}'\`);`,
    `  return spec;`,
    `};`,
    ``,
    `export const FEATURE_PLAN: Readonly<Record<FeaturePriority, readonly (readonly FeatureSpec[])[]>> = {`,
    ...phaseLines.map((line, idx) => (idx < phaseLines.length - 1 ? `${line},` : `${line},`)),
    `};`,
    ``,
  ].join('\n');
}

/**
 * Public entry point. Idempotent: writes only if content changed.
 *
 * @param {object} options
 * @param {string} options.projectRoot — repository root
 * @param {boolean} [options.write=true] — when false, returns the generated source without writing
 * @returns {{ outputPath: string, source: string, changed: boolean }}
 */
export function generateFeaturePlan({ projectRoot, write = true } = {}) {
  const root = projectRoot || path.join(__dirname, '..');
  const specsDir = path.join(root, 'src/main/initializers');
  const outputDir = path.join(root, 'src/main/generated');
  const outputPath = path.join(outputDir, 'featurePlan.ts');

  const specFiles = fs
    .readdirSync(specsDir)
    .filter((f) => f.endsWith('.spec.ts'))
    .sort()
    .map((f) => {
      const fullPath = path.join(specsDir, f);
      const source = fs.readFileSync(fullPath, 'utf-8');
      const exportMatch = source.match(/export\s+const\s+(\w+)\s*=\s*\[/);
      if (!exportMatch) {
        throw new Error(`[featurePlanPlugin] No 'export const NAME = [' in ${f}`);
      }
      const exportName = exportMatch[1];
      const entries = parseSpecFile(source);
      const importPath = `../initializers/${f.replace(/\.ts$/, '.js')}`;
      return { file: f, exportName, importPath, entries };
    });

  const allEntries = specFiles.flatMap((s) => s.entries);
  const knownNames = new Set(allEntries.map((e) => e.name));

  // Verify uniqueness
  const seen = new Set();
  for (const e of allEntries) {
    if (seen.has(e.name)) {
      throw new Error(`[featurePlanPlugin] Duplicate feature name: '${e.name}'`);
    }
    seen.add(e.name);
  }

  const plan = {};
  for (const phase of PHASES) {
    plan[phase] = batchByDependencies(allEntries, phase, knownNames).map((batch) =>
      batch.map((e) => e.name)
    );
  }

  const source = emitPlan(specFiles, plan);

  fs.mkdirSync(outputDir, { recursive: true });
  let changed = true;
  if (fs.existsSync(outputPath)) {
    const prev = fs.readFileSync(outputPath, 'utf-8');
    changed = prev !== source;
  }
  if (write && changed) {
    fs.writeFileSync(outputPath, source);
    console.log(
      `[featurePlanPlugin] Emitted ${path.relative(root, outputPath)} ` +
        `(${allEntries.length} features, ${PHASES.map((p) => `${p}=${plan[p].length}b`).join(', ')})`
    );
  } else if (write) {
    console.log(`[featurePlanPlugin] ${path.relative(root, outputPath)} up to date`);
  }
  return { outputPath, source, changed };
}

/**
 * Rsbuild plugin: regenerates the plan before each compilation (dev/watch + prod).
 */
export const featurePlanPlugin = ({ projectRoot } = {}) => ({
  name: 'feature-plan-codegen',
  setup(api) {
    const run = () => {
      try {
        generateFeaturePlan({ projectRoot });
      } catch (error) {
        // Rspack catches thrown errors during onBeforeBuild and surfaces them.
        console.error('[featurePlanPlugin]', error.message);
        throw error;
      }
    };
    api.onBeforeBuild(run);
    if (api.onBeforeStartDevServer) api.onBeforeStartDevServer(run);
  },
});

export default featurePlanPlugin;
