#!/usr/bin/env node
/**
 * Feature Plan Codegen
 *
 * Reads `src/main/initializers/*.spec.ts`, computes per-phase dependency batches
 * via topological sort, and emits `src/main/generated/featurePlan.ts`.
 *
 * Replaces the runtime topo-sort that used to live in the 485-line
 * FeatureManager. At runtime, `featureRunner` simply walks the precomputed plan.
 *
 * Parsing strategy: spec files have a strict shape (name/phase/dependencies as
 * literal strings/arrays inside `as const satisfies readonly FeatureSpec[]`).
 * We parse them with the official TypeScript Compiler API
 * (`ts.createSourceFile` + `ts.forEachChild`) and read the literal fields off
 * the resulting AST. This is robust against nested braces, comments, template
 * literals, and any whitespace variation that the previous regex-based parser
 * could not safely handle.
 *
 * Exposed as both:
 *   - A standalone function `generateFeaturePlan({ projectRoot, write })`
 *     for build scripts and tests.
 *   - An Rsbuild plugin via the default export, runnable in any Rsbuild
 *     pipeline so the generated file is always up to date with the specs.
 */

import fs from 'fs';
import path from 'path';
import { createRequire } from 'module';
import { fileURLToPath } from 'url';
import prettier from 'prettier';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const requireFromHere = createRequire(import.meta.url);
const ts = requireFromHere('typescript');

const PHASES = ['security', 'critical', 'ui', 'deferred'];

const HEADER = `/**
 * Auto-generated by \`scripts/featurePlanPlugin.js\`. DO NOT EDIT.
 *
 * The plugin reads \`src/main/initializers/*.spec.ts\`, runs a topological sort
 * keyed by \`dependencies\`, and emits a phase → dependency-batched plan that
 * \`featureRunner\` walks at startup.
 */
`;

/**
 * Parse a `*.spec.ts` source string with the TypeScript Compiler API.
 *
 * Returns:
 *   {
 *     exportName: string,          // e.g. 'SECURITY_FEATURES'
 *     entries:    Array<{ name, phase, dependencies?, required?, description? }>
 *   }
 *
 * Throws if no top-level `export const NAME = [ ... ]` array literal is found.
 *
 * @param {string} source   - The TypeScript source text.
 * @param {string} fileName - File name used for diagnostics (no I/O happens).
 */
export function parseSpecSource(source, fileName = 'spec.ts') {
  const sf = ts.createSourceFile(
    fileName,
    source,
    ts.ScriptTarget.Latest,
    /* setParentNodes */ true
  );

  let exportName;
  let arrayLiteral;

  // Walk only the top-level statements. We deliberately do NOT recurse with
  // ts.forEachChild past the variable declaration we care about; nested object
  // literals (inside init/cleanup bodies) are reached via the array-literal
  // children below, never as standalone exports.
  ts.forEachChild(sf, (stmt) => {
    if (arrayLiteral) return;
    if (!ts.isVariableStatement(stmt)) return;
    const isExported = (stmt.modifiers || []).some((m) => m.kind === ts.SyntaxKind.ExportKeyword);
    if (!isExported) return;

    for (const decl of stmt.declarationList.declarations) {
      if (!decl.initializer) continue;
      if (!ts.isIdentifier(decl.name)) continue;

      // Strip outer `expr as const satisfies readonly FeatureSpec[]` wrappers.
      let init = decl.initializer;
      while (
        ts.isAsExpression(init) ||
        ts.isSatisfiesExpression(init) ||
        ts.isParenthesizedExpression(init) ||
        ts.isTypeAssertionExpression(init)
      ) {
        init = init.expression;
      }
      if (ts.isArrayLiteralExpression(init)) {
        exportName = decl.name.text;
        arrayLiteral = init;
        return;
      }
    }
  });

  if (!arrayLiteral || !exportName) {
    throw new Error(`[featurePlanPlugin] No 'export const NAME = [ ... ]' array in ${fileName}`);
  }

  const entries = [];
  for (const element of arrayLiteral.elements) {
    if (!ts.isObjectLiteralExpression(element)) continue;
    const entry = extractFeatureEntry(element);
    if (entry && entry.name && entry.phase) entries.push(entry);
  }

  return { exportName, entries };
}

/**
 * Extract `{ name, phase, required, dependencies, description }` from a single
 * object literal AST node. Properties we don't care about (`init`, `cleanup`,
 * unknown extension fields) are ignored — which is exactly why the AST
 * approach is safer than regex: nested braces / template literals inside those
 * bodies cannot confuse the walker.
 */
function extractFeatureEntry(objLiteral) {
  const result = {};
  for (const prop of objLiteral.properties) {
    if (!ts.isPropertyAssignment(prop)) continue;
    const keyName = propertyKeyName(prop.name);
    if (!keyName) continue;

    switch (keyName) {
      case 'name':
      case 'phase':
      case 'description': {
        const literal = stringLiteralValue(prop.initializer);
        if (literal !== undefined) result[keyName] = literal;
        break;
      }
      case 'required': {
        const init = prop.initializer;
        if (init.kind === ts.SyntaxKind.TrueKeyword) result.required = true;
        else if (init.kind === ts.SyntaxKind.FalseKeyword) result.required = false;
        break;
      }
      case 'dependencies': {
        const init = prop.initializer;
        if (ts.isArrayLiteralExpression(init)) {
          const deps = [];
          for (const el of init.elements) {
            const v = stringLiteralValue(el);
            if (v !== undefined) deps.push(v);
          }
          result.dependencies = deps;
        }
        break;
      }
      default:
        // Ignore init / cleanup / unknown extension fields.
        break;
    }
  }
  return result;
}

function propertyKeyName(nameNode) {
  if (ts.isIdentifier(nameNode)) return nameNode.text;
  if (ts.isStringLiteral(nameNode) || ts.isNoSubstitutionTemplateLiteral(nameNode)) {
    return nameNode.text;
  }
  return undefined;
}

function stringLiteralValue(node) {
  if (!node) return undefined;
  if (ts.isStringLiteral(node) || ts.isNoSubstitutionTemplateLiteral(node)) {
    return node.text;
  }
  return undefined;
}

/**
 * Topologically sort entries within a single phase, returning batches.
 * Cross-phase deps are tolerated (assumed to be initialized in a prior phase).
 * Throws on cycle detection.
 */
function batchByDependencies(entries, phase, knownNames) {
  const inPhase = entries.filter((e) => e.phase === phase);
  const inPhaseNames = new Set(inPhase.map((e) => e.name));

  // Cycle detection via DFS
  const visiting = new Set();
  const visited = new Set();
  const visit = (e) => {
    if (visited.has(e.name)) return;
    if (visiting.has(e.name)) {
      throw new Error(`[featurePlanPlugin] Circular dependency detected at '${e.name}'`);
    }
    visiting.add(e.name);
    for (const dep of e.dependencies || []) {
      const next = inPhase.find((x) => x.name === dep);
      if (next) visit(next);
      else if (!knownNames.has(dep)) {
        throw new Error(`[featurePlanPlugin] '${e.name}' depends on unknown feature '${dep}'`);
      }
    }
    visiting.delete(e.name);
    visited.add(e.name);
  };
  for (const e of inPhase) visit(e);

  // Greedy batch assignment: a feature lands in batch N once all in-phase deps
  // are in batches < N.
  const batches = [];
  const assigned = new Set();
  let remaining = [...inPhase];
  while (remaining.length) {
    const ready = remaining.filter((e) =>
      (e.dependencies || []).every((d) => !inPhaseNames.has(d) || assigned.has(d))
    );
    if (!ready.length) {
      throw new Error(
        `[featurePlanPlugin] Unresolvable dependencies in '${phase}': ${remaining.map((e) => e.name).join(', ')}`
      );
    }
    batches.push(ready);
    for (const e of ready) assigned.add(e.name);
    remaining = remaining.filter((e) => !assigned.has(e.name));
  }
  return batches;
}

async function emitPlan(specFiles, plan) {
  const importLines = specFiles.map(
    ({ exportName, importPath }) => `import { ${exportName} } from '${importPath}';`
  );
  const phaseLines = PHASES.map((phase) => {
    const batches = plan[phase] || [];
    const inner = batches
      .map((batch) => `[${batch.map((name) => `get('${name}')`).join(', ')}]`)
      .join(', ');
    return `  ${phase}: [${inner}]`;
  });
  const raw = [
    HEADER,
    `import type { FeatureSpec, FeaturePriority } from '../utils/lifecycle/featureConfigTypes.js';`,
    ...importLines,
    ``,
    `const ALL_SPECS: readonly FeatureSpec[] = [`,
    ...specFiles.map(({ exportName }) => `  ...${exportName},`),
    `];`,
    ``,
    `const byName = new Map<string, FeatureSpec>(ALL_SPECS.map((s) => [s.name, s]));`,
    `const get = (name: string): FeatureSpec => {`,
    `  const spec = byName.get(name);`,
    `  if (!spec) throw new Error(\`[FEATURE_PLAN] Missing spec for '\${name}'\`);`,
    `  return spec;`,
    `};`,
    ``,
    `export const FEATURE_PLAN: Readonly<Record<FeaturePriority, readonly (readonly FeatureSpec[])[]>> = {`,
    ...phaseLines.map((line) => `${line},`),
    `};`,
    ``,
  ].join('\n');
  return prettier.format(raw, {
    parser: 'typescript',
    printWidth: 100,
    singleQuote: true,
    semi: true,
    trailingComma: 'all',
  });
}

/**
 * Pure (no I/O) plan builder: parses every input spec source, validates
 * uniqueness, runs per-phase topological batching, and emits the final
 * `featurePlan.ts` source string. Used by `generateFeaturePlan` and exposed
 * directly so tests can feed inline spec sources without touching the disk.
 *
 * @param {Array<{ file: string, source: string }>} inputs
 * @returns {{ source: string, plan: Record<string, string[][]>, allEntries: object[] }}
 */
export async function buildPlanFromSources(inputs) {
  const specFiles = inputs.map(({ file, source }) => {
    const { exportName, entries } = parseSpecSource(source, file);
    const importPath = `../initializers/${file.replace(/\.ts$/, '.js')}`;
    return { file, exportName, importPath, entries };
  });

  const allEntries = specFiles.flatMap((s) => s.entries);
  const knownNames = new Set(allEntries.map((e) => e.name));

  // Verify uniqueness
  const seen = new Set();
  for (const e of allEntries) {
    if (seen.has(e.name)) {
      throw new Error(`[featurePlanPlugin] Duplicate feature name: '${e.name}'`);
    }
    seen.add(e.name);
  }

  const plan = {};
  for (const phase of PHASES) {
    plan[phase] = batchByDependencies(allEntries, phase, knownNames).map((batch) =>
      batch.map((e) => e.name)
    );
  }

  const source = await emitPlan(specFiles, plan);
  return { source, plan, allEntries };
}

/**
 * Public entry point. Idempotent: writes only if content changed.
 *
 * @param {object} options
 * @param {string} options.projectRoot — repository root
 * @param {boolean} [options.write=true] — when false, returns the generated source without writing
 * @returns {{ outputPath: string, source: string, changed: boolean }}
 */
export async function generateFeaturePlan({ projectRoot, write = true } = {}) {
  const root = projectRoot || path.join(__dirname, '..');
  const specsDir = path.join(root, 'src/main/initializers');
  const outputDir = path.join(root, 'src/main/generated');
  const outputPath = path.join(outputDir, 'featurePlan.ts');

  const inputs = fs
    .readdirSync(specsDir)
    .filter((f) => f.endsWith('.spec.ts'))
    .sort()
    .map((f) => ({
      file: f,
      source: fs.readFileSync(path.join(specsDir, f), 'utf-8'),
    }));

  const { source, plan, allEntries } = await buildPlanFromSources(inputs);

  fs.mkdirSync(outputDir, { recursive: true });
  let changed = true;
  if (fs.existsSync(outputPath)) {
    const prev = fs.readFileSync(outputPath, 'utf-8');
    changed = prev !== source;
  }
  if (write && changed) {
    fs.writeFileSync(outputPath, source);
    console.log(
      `[featurePlanPlugin] Emitted ${path.relative(root, outputPath)} ` +
        `(${allEntries.length} features, ${PHASES.map((p) => `${p}=${plan[p].length}b`).join(', ')})`
    );
  } else if (write) {
    console.log(`[featurePlanPlugin] ${path.relative(root, outputPath)} up to date`);
  }
  return { outputPath, source, changed };
}

/**
 * Rsbuild plugin: regenerates the plan before each compilation (dev/watch + prod).
 */
export const featurePlanPlugin = ({ projectRoot } = {}) => ({
  name: 'feature-plan-codegen',
  setup(api) {
    const run = async () => {
      try {
        await generateFeaturePlan({ projectRoot });
      } catch (error) {
        // Rspack catches thrown errors during onBeforeBuild and surfaces them.
        console.error('[featurePlanPlugin]', error.message);
        throw error;
      }
    };
    api.onBeforeBuild(run);
    if (api.onBeforeStartDevServer) api.onBeforeStartDevServer(run);
  },
});

export default featurePlanPlugin;
